name: Build and Dockerize Java API

# Trigger the workflow on any commit to any branch
on: [push]

jobs:
  # Job 1: Build the application
  job1:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
  
    # Add this step to fix permission issue with mvnw during GitHub Actions build
    - name: Grant execution permission for Maven wrapper
      run: chmod +x ./mvnw
  
    - name: Build the application
      run: ./mvnw clean package

  # Job 2: Build and push Docker image
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rest-bookstore-service:latest .
      
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/rest-bookstore-service:latest
