#name: Hello World Build Pipeline

# Trigger the workflow on any commit to any branch
#on: 
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

#jobs:
#  build:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3

#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        distribution: 'temurin'
#        java-version: '17'

#    - name: Hello World build step
#      run: echo "Hello, World! The build pipeline is running on JDK 17!"

name: Build and Dockerize Java API

# Trigger the workflow on any commit to any branch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Add this step to fix permission issue with mvnw
    - name: Grant execution permission for Maven wrapper
      run: chmod +x ./mvnw

    - name: Build the application
      run: ./mvnw clean package  # Or './gradlew build' if you're using Gradle

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rest-bookstore-service:latest .
    
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/rest-bookstore-service:latest

