name: Build and Dockerize Java API

# Trigger the workflow on any commit to any branch
on: [push]

jobs:
  # Job 1: Build the application
  job1:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
  
    # Add this step to fix permission issue with mvnw during GitHub Actions build
    - name: Grant execution permission for Maven wrapper
      run: chmod +x ./mvnw
  
    - name: Build the application
      run: ./mvnw clean package

  # Job 2: Build and push Docker image to Azure Container Registry
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set version tag
      id: set_version
      run: echo "VERSION_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login brightstraining24fall.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t brightstraining24fall.azurecr.io/rest-bookstore-service:${{ env.VERSION_TAG }} .

    - name: Push Docker image to Azure Container Registry
      run: docker push brightstraining24fall.azurecr.io/rest-bookstore-service:${{ env.VERSION_TAG }}
